spring:
  ## For docker
  kafka:
    bootstrap-servers: kafka:29092
  cache:
    type: redis
  data:
    redis:
      ## For docker
      host: redis
      ## Without docker
      #host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres