spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres