spring:
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres